id: opecha:P007947
initial_creation_type: ocr
source_metadata:
  id: bdr:W23728
  title: གསང་བ་སྒྱུ་འཕྲུལ་ཞི་ཁྲོ་གཉིས་ཀྱི་རྩ་འཆམས་བྱུང་ཁུངས་ལོ་རྒྱུས་རྩ་ཚིག་བཅས་གོ་གསལ་དུ་བཀོད་པ་བཞུགས་སོ
  volume: ''
  author: ''
