id: opecha:P007947
initial_creation_type: ocr
source_metadata:
  id: bdr:W23728
  title: གསང་བ་སྒྱུ་འཕྲུལ་ཞི་ཁྲོ་གཉིས་ཀྱི་རྩ་འཆམས་བྱུང་ཁུངས་ལོ་རྒྱུས་རྩ་ཚིག་བཅས་གོ་གསལ་དུ་བཀོད་པ་བཞུགས་སོ
  volume:
    ea27c73998314823984ec04aea5b5fe5:
      image_group_id: I2528
      title: ''
      volume_number: 1
      total_pages: 34
  author: ''
  volumes:
    fe7e38eee8ed47998119938d59d46fea:
      image_group_id: I2528
      title: ''
      volume_number: 1
      total_pages: 34
ebook_metadata:
  title: གསང་བ་སྒྱུ་འཕྲུལ་ཞི་ཁྲོ་གཉིས་ཀྱི་རྩ་འཆམས་བྱུང་ཁུངས་ལོ་རྒྱུས་རྩ་ཚིག་བཅས་གོ་གསལ་དུ་བཀོད་པ་བཞུགས་སོ
  author: ''
  sku: P007947
  cover: cover.jpg
  layers:
  - pagination
